import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import Link from "next/link";
import Navigation from "./components/Navigation";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="text-4xl">
        <Navigation/> 
        </div>
        <Header/>
        <div className="text-3xl">
        {children}
        </div>
        </body>
        <br />
      <div className="text-2xl">
      <Footer/>
      </div>
      
    </html>
  );
}
