import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import Link from "next/link";
import Navigation from "./components/Navigation";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <link href="https://fonts.googleapis.com/css2?family=Sarabun:wght@300;400;600&display=swap" rel="stylesheet"></link>
      <body className={inter.className }>
        <div className="text-2xl" style={{ fontFamily: 'Sarabun, sans-serif' }}>
        <Navigation/> 
        </div>
        <Header/>
        <div className="text-2xl" style={{ fontFamily: 'Sarabun, sans-serif' }} >
        {children}
        </div>
        </body>
        <br />
      <div className="">
      <Footer/>
      </div>
      
    </html>
  );
}
